### ISSUE TITLE
Instagram blocking access to site completely when extension is used & turned on. when turned off, site works.

### ISSUE THREAD

**Issue by Username23453** [omidnikrah/anonymous-instagram-story-seen#6]
This issue is not a big deal actually, if i just turn it off once i am done looking at insta stories, i dont ever get this issue. I also want to express here a thank you & appreciation to omidnikrah for making this extension. :) I've been using it for a long time.

 ![image](https://github.com/omidnikrah/anonymous-instagram-story-seen/assets/105397593/7832fa54-355b-4735-a95b-bcc62690f578)

**Comment by thefanaticid** [comment]
You can modify backround.js like this to specify blocking request. So far it's working very well for me

chrome.webRequest.onBeforeRequest.addListener(
	function (details) {
		const formData = details.requestBody.formData
		const statusBlocking = (JSON.parse(formData.variables[0]).viewSeenAt && details.method == "POST") ? true : false ;
		
		return { cancel: (isActive && statusBlocking) }
	},
	{ urls: [ '*://*.instagram.com/api/*/stories/reel/seen*', '*://*.instagram.com/api/graphql*' ] },
	[ 'blocking', 'requestBody']
);

**Comment by sbhbhrtui** [comment]
the extension dont work well. when i click on any story, the site crash, and pop up the massage "something went wrong" just like in the first comments. please fix that problem. tnx to omidnikrah for this amazing extension!!..

**Comment by thefanaticid** [comment]
The problem arises because instagram moved some of their main functions to grapql, if omidnikrah blocks the grapql* url pattern then everything will be affected. Then I tried to detect which part is specifically for sending story viewer lists. Actually there are several ways to be able to do it, in the example I gave I detected through the data form provided. If there is viewSeenAt then block the request. 

Change background.js in the chrome.webRequest.onBeforeRequest.addListener section, don't replace the entire contents of the file with the code I gave.

If that still doesn't work I don't know if instagram has different requests in each region. In my region it still works fine

**Comment by sbhbhrtui** [comment]
@thefanaticid tnx for the replay, Unfortunately I don't know much about programming and fixing extensions. i hope that omidnikrah or someone else can able solve the problem.  this is my favorite extension and i really love and need it. I will continue to wait patiently for the problem to be resolved. tnx again to everyone that doing this good job..

**Comment by arig241** [comment]
> You can modify backround.js like this to specify blocking request. So far it's working very well for me
> 
> ```
> chrome.webRequest.onBeforeRequest.addListener(
> 	function (details) {
> 		const formData = details.requestBody.formData
> 		const statusBlocking = (JSON.parse(formData.variables[0]).viewSeenAt && details.method == "POST") ? true : false ;
> 		return { cancel: (isActive && statusBlocking) }
> 	},
> 	{ urls: [ '*://*.instagram.com/api/*/stories/reel/seen*', '*://*.instagram.com/api/graphql*' ] },
> 	[ 'blocking', 'requestBody']
> );
> ```

It's been working great, I did something similar, but in the recent couple of days it started doing some really weird thing where it still view the current story anonymously (meaning the request on current story is blocked), yet it automatically marks the next 3 or 4 stories of the next accounts in order as seen, meaning if you have the stories of person1, p2,p3,p4, and you click on p1, p1 stays unseen yet p2,p3,p4 are all seen. I haven't been able to crack down how to which request is responsible for it and how to avoid that, any idea?

**Comment by jesseger** [comment]
@arig241 Do you have any idea how to reproduce this?

**Comment by arig241** [comment]
> @arig241 Do you have any idea how to reproduce this?

Using desktop Google Chrome with Instagram web app, clicking an account story through the homepage story nav-bar, with an implemented functionality of blocking the entire XHR request if it contains the field "ViewSeenAt", marks the next couple of accounts stories as seen.
I tested it logging in to a different account that the main one it's been happening on, on the same browser, with the same chrome blocking functionality and it wasn't able to reproduce it on the second account, yet it continues on the first. Any idea on that would be possible?
